/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--background-rgb) / <alpha-value>)',
        foreground: 'rgb(var(--foreground-rgb) / <alpha-value>)',
        card: 'rgb(var(--card-rgb) / <alpha-value>)',
        border: 'rgb(var(--border-rgb) / <alpha-value>)',
        input: 'rgb(var(--input-rgb) / <alpha-value>)',
        muted: 'rgb(var(--muted-rgb) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--muted-foreground-rgb) / <alpha-value>)',
        primary: 'rgb(var(--primary-rgb) / <alpha-value>)',
        'primary-foreground': 'rgb(var(--primary-foreground-rgb) / <alpha-value>)',
        'primary-hover': 'rgb(var(--primary-hover-rgb) / <alpha-value>)',
        'primary-active': 'rgb(var(--primary-active-rgb) / <alpha-value>)',
        'primary-soft': 'rgb(var(--primary-soft-rgb) / <alpha-value>)',
        'primary-subtle': 'rgb(var(--primary-subtle-rgb) / <alpha-value>)',
        accent: 'rgb(var(--accent-rgb) / <alpha-value>)',
        'accent-foreground': 'rgb(var(--accent-foreground-rgb) / <alpha-value>)',
        destructive: 'rgb(var(--destructive-rgb) / <alpha-value>)',
        'destructive-soft': 'rgb(var(--destructive-soft-rgb) / <alpha-value>)',
        'destructive-border': 'rgb(var(--destructive-border-rgb) / <alpha-value>)',
        warning: 'rgb(var(--warning-rgb) / <alpha-value>)',
        'warning-foreground': 'rgb(var(--warning-foreground-rgb) / <alpha-value>)',
        'warning-solid': 'rgb(var(--warning-solid-rgb) / <alpha-value>)',
        'warning-border': 'rgb(var(--warning-border-rgb) / <alpha-value>)',
        success: 'rgb(var(--success-rgb) / <alpha-value>)',
        'success-foreground': 'rgb(var(--success-foreground-rgb) / <alpha-value>)',
        'success-soft': 'rgb(var(--success-soft-rgb) / <alpha-value>)',
        'success-border': 'rgb(var(--success-border-rgb) / <alpha-value>)',
        info: 'rgb(var(--info-rgb) / <alpha-value>)',
        'info-soft': 'rgb(var(--info-soft-rgb) / <alpha-value>)',
        'info-border': 'rgb(var(--info-border-rgb) / <alpha-value>)',
        midnight: 'rgb(var(--midnight-rgb) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        title: ['Poppins', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        xl: '0.625rem',
        lg: '0.5rem',
        md: '0.375rem',
        sm: '0.25rem',
      },
    },
  },
  plugins: [],
}
